/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipitMainWhipRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLGowhipitMainWhipRequest (0 custom class methods, 2 custom properties)

#import "GTLGowhipitMainWhipRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLGowhipitMainWhipRequest
//

@implementation GTLGowhipitMainWhipRequest
@dynamic imgName, imgUrl;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"imgName" : @"img_name",
    @"imgUrl" : @"img_url"
  };
  return map;
}

@end
