/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipitMainResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLGowhipitMainResponse (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGowhipitMainResponse
//

@interface GTLGowhipitMainResponse : GTLObject
@property (nonatomic, copy) NSString *status;
@property (nonatomic, retain) NSNumber *uploadTot;  // longLongValue
@property (nonatomic, retain) NSNumber *uploadsRem;  // longLongValue
@end
