/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipit_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API

#import "GTLGowhipitConstants.m"

#import "GTLGowhipitMainResponse.m"
#import "GTLGowhipitMainWhipRequest.m"

#import "GTLQueryGowhipit.m"
#import "GTLServiceGowhipit.m"
