/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipitMainResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLGowhipitMainResponse (0 custom class methods, 3 custom properties)

#import "GTLGowhipitMainResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLGowhipitMainResponse
//

@implementation GTLGowhipitMainResponse
@dynamic status, uploadTot, uploadsRem;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"uploadsRem" : @"uploads_rem",
    @"uploadTot" : @"upload_tot"
  };
  return map;
}

@end
