/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipitMainWhipRequest.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLGowhipitMainWhipRequest (0 custom class methods, 2 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLGowhipitMainWhipRequest
//

// Greeting that stores a message.

@interface GTLGowhipitMainWhipRequest : GTLObject
@property (nonatomic, copy) NSString *imgName;
@property (nonatomic, copy) NSString *imgUrl;
@end
