/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipitConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API

#import "GTLGowhipitConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeGowhipitUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
