/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLGowhipit.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API

#import "GTLGowhipitConstants.h"

#import "GTLGowhipitMainResponse.h"
#import "GTLGowhipitMainWhipRequest.h"

#import "GTLQueryGowhipit.h"
#import "GTLServiceGowhipit.h"
