/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryGowhipit.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryGowhipit (2 custom class methods, 1 custom properties)

#import "GTLQueryGowhipit.h"

#import "GTLGowhipitMainResponse.h"
#import "GTLGowhipitMainWhipRequest.h"

@implementation GTLQueryGowhipit

@dynamic fields;

#pragma mark - Service level methods
// These create a GTLQueryGowhipit object.

+ (instancetype)queryForPostUploadWithObject:(GTLGowhipitMainWhipRequest *)object {
  if (object == nil) {
    GTL_DEBUG_ASSERT(object != nil, @"%@ got a nil object", NSStringFromSelector(_cmd));
    return nil;
  }
  NSString *methodName = @"gowhipit.post_upload";
  GTLQueryGowhipit *query = [self queryWithMethodName:methodName];
  query.bodyObject = object;
  query.expectedObjectClass = [GTLGowhipitMainResponse class];
  return query;
}

+ (instancetype)queryForUploadsLeft {
  NSString *methodName = @"gowhipit.uploads_left";
  GTLQueryGowhipit *query = [self queryWithMethodName:methodName];
  query.expectedObjectClass = [GTLGowhipitMainResponse class];
  return query;
}

@end
