/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLQueryGowhipit.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   gowhipit/v1
// Description:
//   This is an API
// Classes:
//   GTLQueryGowhipit (2 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLGowhipitMainWhipRequest;

@interface GTLQueryGowhipit : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (nonatomic, copy) NSString *fields;

#pragma mark - Service level methods
// These create a GTLQueryGowhipit object.

// Method: gowhipit.post_upload
//  Authorization scope(s):
//   kGTLAuthScopeGowhipitUserinfoEmail
// Fetches a GTLGowhipitMainResponse.
+ (instancetype)queryForPostUploadWithObject:(GTLGowhipitMainWhipRequest *)object;

// Method: gowhipit.uploads_left
//  Authorization scope(s):
//   kGTLAuthScopeGowhipitUserinfoEmail
// Fetches a GTLGowhipitMainResponse.
+ (instancetype)queryForUploadsLeft;

@end
